"use client";
import { useCallback, useEffect, useState } from "react";
import { Check, ChevronDown, Download, LoaderCircle, RefreshCw, TriangleAlert } from "lucide-react";
import { api } from "@/lib/api";
import { useT, type TranslationKey } from "@/lib/i18n";
import { formatBytes, formatDuration } from "@/lib/utils";
import { useToast } from "@/stores/toast";
import type { ImageAsset, ProcessingSettings } from "@/types/api";
import { Button } from "@/components/ui/button";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/ui/badge";

type Background = "checkerboard" | "white" | "black" | "custom";
const BACKGROUND_PRESETS: { id: Background; hex: string }[] = [
  { id: "checkerboard", hex: "" }, { id: "white", hex: "#ffffff" }, { id: "black", hex: "#000000" },
];
export function ImageDetail({ imageId }: { imageId: string }) {
  const [image, setImage] = useState<ImageAsset | null>(null); const [error, setError] = useState(""); const [position, setPosition] = useState(50);
  const [background, setBackground] = useState<Background>("checkerboard"); const [custom, setCustom] = useState("#d9ecff"); const [advanced, setAdvanced] = useState(false); const [saving, setSaving] = useState(false); const toast = useToast();
  const { t } = useT();
  const load = useCallback(async () => { try { setImage(await api.getImage(imageId)); setError(""); } catch (e) { setError(e instanceof Error ? e.message : t("image.loading")); } }, [imageId, t]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  if (error && !image) return <div className="surface p-10 text-center"><TriangleAlert className="mx-auto text-red-500" /><p className="mt-3 font-semibold">{error}</p><Button className="mt-4" onClick={load}>{t("common.retry")}</Button></div>;
  if (!image) return <div className="grid min-h-[50vh] place-items-center text-sm text-black/45"><LoaderCircle className="animate-spin" /> {t("image.loading")}</div>;
  const processed = ["COMPLETED","NEEDS_REVIEW"].includes(image.status); const settings = image.processing_settings;
  const update = <K extends keyof ProcessingSettings>(key: K, value: ProcessingSettings[K]) => setImage({ ...image, processing_settings: { ...settings, [key]: value } });
  async function reprocess() { setSaving(true); try { await api.updateSettings(image!.id, settings); await api.reprocess(image!.id); toast.show(t("image.toast.reprocessed"), "success"); await load(); } catch (e) { toast.show(e instanceof Error ? e.message : t("image.toast.reprocessFailed"), "error"); } finally { setSaving(false); } }
  async function approve() { try { setImage(await api.approve(image!.id)); toast.show(t("image.toast.approved"), "success"); } catch (e) { toast.show(e instanceof Error ? e.message : t("image.toast.approveFailed"), "error"); } }
  const previewHex = background === "custom" ? custom : BACKGROUND_PRESETS.find((preset) => preset.id === background)?.hex;
  const previewStyle = background === "checkerboard" || !previewHex ? undefined : { backgroundColor: previewHex };
  return <><PageHeading eyebrow={t("image.eyebrow")} title={image.original_filename} backHref={`/jobs/${image.job_id}`} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
      <section className="surface overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-black/[.06] p-4"><div className="flex items-center gap-2"><StatusBadge status={image.status} /><span className="text-xs text-black/40">{t("image.compareHint")}</span></div><div className="flex gap-1 rounded-lg bg-fog p-1">{(["checkerboard","white","black"] as Background[]).map((item) => <button key={item} onClick={() => setBackground(item)} className={`focus-ring rounded-md px-2.5 py-1.5 text-[10px] font-bold ${background === item ? "bg-white shadow-sm" : "text-black/45"}`}>{t(`image.bg.${item}` as TranslationKey)}</button>)}<label className={`focus-ring cursor-pointer rounded-md px-2.5 py-1.5 text-[10px] font-bold ${background === "custom" ? "bg-white shadow-sm" : "text-black/45"}`}>{t("image.bg.custom")}<input type="color" className="sr-only" value={custom} onChange={(e) => { setCustom(e.target.value); setBackground("custom"); }} /></label></div></div>
        <div className={`${background === "checkerboard" ? "checkerboard" : ""} relative aspect-[4/3] overflow-hidden`} style={previewStyle}>{processed ? <><img src={api.assetUrl(image.id,"original")} alt={t("image.original")} className="absolute inset-0 size-full object-contain" /><img src={api.assetUrl(image.id,"transparent")} alt={t("image.processed")} className="absolute inset-0 size-full object-contain" style={{ clipPath: `inset(0 ${100 - position}% 0 0)` }} /><div className="pointer-events-none absolute inset-y-0 w-0.5 bg-white shadow-xl" style={{ left: `${position}%` }}><span className="absolute left-1/2 top-1/2 grid size-8 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white text-xs font-bold text-black shadow-lg">↔</span></div><input aria-label={t("image.compareHint")} type="range" min={0} max={100} value={position} onChange={(e) => setPosition(Number(e.target.value))} className="absolute inset-0 z-10 size-full cursor-ew-resize opacity-0" /></> : <div className="grid size-full place-items-center text-center"><div><LoaderCircle className={`mx-auto ${image.status === "PROCESSING" ? "animate-spin" : ""} text-black/25`} /><p className="mt-3 text-sm font-semibold">{image.status === "FAILED" ? t("image.failed") : t("image.notReady")}</p>{image.error_message && <p className="mx-auto mt-1 max-w-md text-xs text-red-600">{image.error_message}</p>}</div></div>}</div>
        <div className="grid grid-cols-2 border-t border-black/[.06] text-center text-[10px] font-bold uppercase tracking-widest text-black/40"><span className="border-r border-black/[.06] py-3">{t("image.original")}</span><span className="py-3">{t("image.processed")}</span></div>
      </section>
      <aside className="space-y-5"><section className="surface p-5"><p className="eyebrow mb-4">{t("image.qc")}</p><div className="flex items-end justify-between"><p className="text-sm font-semibold">{t("image.qualityScore")}</p><p className="text-3xl font-semibold tracking-tight">{image.quality_score ?? "—"}<span className="text-sm text-black/35"> / 100</span></p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-black/[.06]"><div className={`h-full ${image.quality_score != null && image.quality_score >= 85 ? "bg-emerald-500" : "bg-amber-500"}`} style={{ width: `${image.quality_score ?? 0}%` }} /></div><div className="mt-4 flex flex-wrap gap-1.5">{image.quality_flags.length ? image.quality_flags.map((flag) => <span key={flag} className="rounded-md bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-800">{flag.replaceAll("_"," ")}</span>) : <span className="text-xs text-black/40">{t("image.noFlags")}</span>}</div>{image.status === "NEEDS_REVIEW" && <Button variant="accent" className="mt-5 w-full" onClick={approve}><Check size={16} /> {t("image.approve")}</Button>}</section>
        <section className="surface p-5"><p className="eyebrow mb-4">{t("image.settings")}</p><Range label={t("image.edgeCleanup")} value={settings.edge_cleanup} min={0} max={1} step={0.05} onChange={(v) => update("edge_cleanup",v)} /><Range label={t("image.feather")} value={settings.feather} min={0} max={5} step={0.1} onChange={(v) => update("feather",v)} /><Toggle label={t("image.removeHalo")} checked={settings.remove_halo} onChange={(v) => update("remove_halo",v)} /><Toggle label={t("image.keepShadow")} checked={settings.keep_natural_shadow} onChange={(v) => update("keep_natural_shadow",v)} /><button onClick={() => setAdvanced(!advanced)} className="mt-3 flex w-full items-center justify-between border-t border-black/[.06] pt-3 text-xs font-semibold">{t("image.advanced")} <ChevronDown size={15} className={advanced ? "rotate-180" : ""} /></button>{advanced && <div className="mt-3 space-y-3"><Toggle label={t("image.removeIslands")} checked={settings.remove_small_islands} onChange={(v) => update("remove_small_islands",v)} /><Toggle label={t("image.fillHoles")} checked={settings.fill_holes} onChange={(v) => update("fill_holes",v)} /><Range label={t("image.smoothness")} value={settings.mask_smoothness} min={0} max={1} step={0.05} onChange={(v) => update("mask_smoothness",v)} /></div>}<Button className="mt-5 w-full" onClick={reprocess} disabled={saving || image.status === "PROCESSING"}><RefreshCw size={16} /> {saving ? t("image.saving") : t("image.reprocess")}</Button></section>
        <section className="surface p-5"><p className="eyebrow mb-4">{t("image.details")}</p><dl className="space-y-2 text-xs">{[[t("image.resolution"),`${image.width} × ${image.height}`],[t("image.fileSize"),formatBytes(image.file_size)],[t("image.processingTime"),formatDuration(image.processing_time_ms)],[t("image.model"),image.model_name ?? "—"],[t("image.version"),image.model_version ?? "—"]].map(([term,value]) => <div key={term} className="flex justify-between gap-4"><dt className="text-black/40">{term}</dt><dd className="truncate font-medium">{value}</dd></div>)}</dl>{processed && <div className="mt-5 grid gap-2"><DownloadLink href={api.assetUrl(image.id,"transparent",true)}>{t("image.download.transparent")}</DownloadLink><DownloadLink href={api.assetUrl(image.id,"white.png",true)}>{t("image.download.whitePng")}</DownloadLink><DownloadLink href={api.assetUrl(image.id,"white.jpg",true)}>{t("image.download.whiteJpg")}</DownloadLink></div>}</section>
      </aside>
    </div></>;
}
function Range({ label,value,min,max,step,onChange }: { label:string; value:number; min:number; max:number; step:number; onChange:(v:number)=>void }) { return <label className="mb-4 block"><span className="mb-2 flex justify-between text-xs font-medium"><span>{label}</span><span className="text-black/40">{value}</span></span><input className="w-full accent-moss" type="range" value={value} min={min} max={max} step={step} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
function Toggle({ label,checked,onChange }: { label:string; checked:boolean; onChange:(v:boolean)=>void }) { return <label className="mb-3 flex cursor-pointer items-center justify-between text-xs font-medium"><span>{label}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="size-4 accent-moss" /></label>; }
function DownloadLink({ href,children }: { href:string; children:React.ReactNode }) { return <Button asChild variant="outline" size="sm" className="w-full"><a href={href}><Download size={14} />{children}</a></Button>; }